# Generated by Django 5.1.6 on 2025-05-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait_1', '0003_remove_abcmodel_result_alter_abcmodel_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abcmodel',
            old_name='task',
            new_name='fam',
        ),
        migrations.AlterField(
            model_name='abcmodel',
            name='current_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
