# Generated by Django 5.1.6 on 2025-05-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait_1', '0004_rename_task_abcmodel_fam_alter_abcmodel_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_content',
            field=models.TextField(default='Проверка сайта', verbose_name='Основное содержание страницы'),
        ),
    ]
