# Generated by Django 5.1.6 on 2025-05-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sait_1', '0005_alter_item_item_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_title'], name='sait_1_item_item_ti_646ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_nav_position'], name='sait_1_item_item_na_e4629c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_current_date'], name='sait_1_item_item_cu_4ea685_idx'),
        ),
    ]
