# Generated by Django 5.1.6 on 2025-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sait_1', '0006_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-item_nav_position',), 'verbose_name': 'Содержание текущей страницы', 'verbose_name_plural': 'Содержание всех страниц'},
        ),
    ]
