# Generated by Django 5.1.6 on 2025-05-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sait_1', '0007_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('item_nav_position',), 'verbose_name': 'Содержание текущей страницы', 'verbose_name_plural': 'Содержание всех страниц'},
        ),
    ]
