# Generated by Django 5.1.6 on 2025-05-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sait_1', '0008_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-item_nav_position',), 'verbose_name': 'Содержание текущей страницы', 'verbose_name_plural': 'Содержание всех страниц'},
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='sait_1_item_item_ti_646ae5_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='sait_1_item_item_na_e4629c_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='sait_1_item_item_cu_4ea685_idx',
        ),
    ]
